config/routes.rb
SendMeALink::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  resources :group_registrations, only: [:new, :create]

  resources :groups, only: [:show]

  constraints(Subdomain) do
    match '/' => 'groups#show'
  end

  root :to => "group_registrations#new"

end

app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/group.rb
class Group
  include Mongoid::Document

  field :name
  field :slug
  field :description
  field :created_at, type: DateTime, default: Time.now
  field :not_approved_users, type: Array, default: []

  attr_accessible :name, :slug, :description,
                  :not_approved_users, :owners_attributes,
                  :participants_attributes

  validates :name, uniqueness: true, presence: true
  validates :slug, uniqueness: true, presence: true

  has_and_belongs_to_many :owners, class_name: "User", inverse_of: :owned_groups
  has_and_belongs_to_many :participants, class_name: "User", inverse_of: :groups

  accepts_nested_attributes_for :owners #, :participants

  index({ name: 1 }, { unique: true, name: "name_index" })
  index({ slug: 1 }, { unique: true, name: "slug_index" })

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates :email, uniqueness: true, presence: true, format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  attr_accessible :email, :password

  index({ email: 1 }, { unique: true, name: "email_index" })

  has_and_belongs_to_many :owned_groups, class_name: "Group", inverse_of: :owners
  has_and_belongs_to_many :participating_groups, class_name: "Group", inverse_of: :participants

  def groups
    owned_groups.concat participating_groups
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/group_registrations_controller.rb
class GroupRegistrationsController < InheritedResources::Base
  defaults :resource_class => Group, :collection_name => 'groups', :instance_name => 'group'
  actions :new, :create
  respond_to :html


  def create
    create! do |success, failure|
      failure.html { redirect_to :back }
      success.html do
        sign_in(:user, resource.owners.last)
        redirect_to resource
      end
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < InheritedResources::Base
  actions :show
  respond_to :html
  before_filter :authenticate_user!

  private

    def resource
      current_user.groups.find_by(slug: request.subdomain)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/group_registrations/new.html.slim
h1 class="title" Send Me a Link

section class="left-column"
  p
    BLOOD ON ICE is a legend among those who have followed us throughout the years. Never permitted to forget about its existence, constantly reminded of it as I was by all the tens of thousands of letters from our fans that I've received throughout the years ever since I breathed about it in the press some years ago, Blood On Ice seemed a very difficult piece of gravel to get out of my shoe.
    It seemed to all these thousands of fans and fanzines a frustrating fact that we could let a complete epic-type of a theme-album collect dust on a shelf. The truth is it was, of course, far from that complete, ready-to-be-released epic creation of a theme- album it was made out to be...
    BLOOD ON ICE is a legend among those who have followed us throughout the years. Never permitted to forget about its existence, constantly reminded of it as I was by all the tens of thousands of letters from our fans that I've received throughout the years ever since I breathed about it in the press some years ago, Blood On Ice seemed a very difficult piece of gravel to get out of my shoe.
    It seemed to all these thousands of fans and fanzines a frustrating fact that we could let a complete epic-type of a theme-album collect dust on a shelf. The truth is it was, of course, far from that complete, ready-to-be-released epic creation of a theme- album it was made out to be...

section class="right-column"
  div class="simple_forms"
    = simple_form_for(resource, url: group_registrations_path) do |f|
      div id="input_fields"
        = f.input :name, placeholder: 'Your group name', label: false
        = f.simple_fields_for(:owners_attributes) do |o|
          = o.input :email, placeholder: 'Your email', label: false, input_html: {name: "group[owners_attributes][][email]"}
          = o.input :password, placeholder: 'Your password', label: false, input_html: {name: "group[owners_attributes][][password]"}
        = f.input :slug, placeholder: 'your-login', label: false

      = f.button :submit, 'Register Free', class: 'btn-primary btn-registr'
      = f.button :submit, 'Register Premium', class: 'btn-primary btn-registr', disabled: true

    div id="checkboxs"
      input type="checkbox" class="checkbox" checked="checked"

    i class="quest icon-question-sign"

footer
  p © Company 2012

app/views/groups/show.html.slim
h1 #{resource.name} group
p Hi to you, dear #{current_user.email}

app/views/home/index.html.slim
'TEST

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible"
    meta content="width=(device-width,)initial-scale=1.0" name="viewport"
    title= content_for?(:title) ? yield(:title) : "SendMeALink"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
    | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>

    = stylesheet_link_tag "application", :media => "all"

    = javascript_include_tag "application"

    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'

    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'

    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'

    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon'
  body
    = yield